---
- name: Prepare mina node for ansible
  hosts: all
  become: yes

  tasks:
    - name: Add mina user and grant sudo rights
      user:
        name: "{{ mina_user }}"
        group: sudo
        shell: /bin/bash
        update_password: on_create
        password: "{{ become_pass | password_hash('sha512') }}"
    - name: Add public SSH key to mina user
      authorized_key:
        user: "{{ mina_user }}"
        state: present
        key: "{{ pub_key }}"

    - name: Create directory for mina keys
      file:
        path: "/home/{{ mina_user }}/keys"
        state: directory
        owner: "{{ mina_user }}"
        mode: '0700'

    - name: Copy wallet's private key to a droplet
      copy:
        src: "{{ mina_wallet }}"
        dest: "/home/{{ mina_user }}/keys/my-wallet"
        owner: "{{ mina_user }}"
        mode: '0600'
      when: mina_wallet

    - name: Copy wallet's public key to a droplet
      copy:
        src: "{{ mina_wallet }}.pub"
        dest: "/home/{{ mina_user }}/keys/my-wallet.pub"
        owner: "{{ mina_user }}"
        mode: '0644'
      when: mina_wallet
